Resources:
  PeopleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.peopleTable}
      AttributeDefinitions:
        - AttributeName: dni
          AttributeType: S
      KeySchema:
        - AttributeName: dni
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
